
name: 'Deploy react app to github pages'
description: 'This action will automate the process of building and depolying react app in gh-pages branch.'
author: 'tanwanimohit'
branding:
  color: blue
  icon: code
runs: 
  using: 'composite'
  steps: 
    - run : npx lerna bootstrap
      shell: bash
    - run : cd ./packages/frontend-react/ && npm run build
      shell: bash
    - run : git config user.name github-actions
      shell: bash
    - run : git config user.email github-actions@github.com
      shell: bash
    - run : git add --force ./packages/frontend-react/build
      shell: bash
    - run : git commit -m "Automatic Deploy action run by github-actions"
      shell: bash
    - run : git push origin HEAD:gh-pages --force
      shell: bash